landingpage:
  image:
    name: eu.gcr.io/vocal-territory-126312/jupyter-landing-page
    tag: "2018-02-01-16-11"
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
  imagePullPolicy: IfNotPresent

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - try.imandra.ai

  hub:
    baseUrl: /h/

  singleuser:
    image:
      name: eu.gcr.io/vocal-territory-126312/jupyter-imandra
      tag: "2018-02-01-16-11"
    storage:
      type: none
    memory:
       limit: 250M
       guarantee: 250M
  
  cull:
    timeout: 300
    every: 60
  
  auth:
    type: tmp

  proxy:
    service:
      type: NodePort
  #   https:
  #     hosts:
  #       - try.imandra.ai
  #     letsencrypt:
  #       contactEmail: dave@aestheticintegration.com
