apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: landing-page
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: landing-page
        component: landing-page
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      nodeSelector: {}
      containers:
      - name: nginx
        image: {{ .Values.landingpage.image.name }}:{{ .Values.landingpage.image.tag }}
        resources:
{{ toYaml .Values.landingpage.resources | indent 12}}
        imagePullPolicy: {{ .Values.landingpage.imagePullPolicy }}
        ports:
          - containerPort: 80
            name: http-pod
