apiVersion: v1
kind: Service
metadata:
  name: landing-page
spec:
  type: NodePort
  selector:
    name: landing-page
    component: landing-page
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: http-pod
